// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: trade_bot_protobuf/src/tradeevent.proto

package tradeevent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespCode  int64  `protobuf:"varint,1,opt,name=resp_code,json=respCode,proto3" json:"resp_code,omitempty"`
	EventCode int64  `protobuf:"varint,2,opt,name=event_code,json=eventCode,proto3" json:"event_code,omitempty"`
	Info      string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Event     string `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *EventProto) Reset() {
	*x = EventProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trade_bot_protobuf_src_tradeevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProto) ProtoMessage() {}

func (x *EventProto) ProtoReflect() protoreflect.Message {
	mi := &file_trade_bot_protobuf_src_tradeevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProto.ProtoReflect.Descriptor instead.
func (*EventProto) Descriptor() ([]byte, []int) {
	return file_trade_bot_protobuf_src_tradeevent_proto_rawDescGZIP(), []int{0}
}

func (x *EventProto) GetRespCode() int64 {
	if x != nil {
		return x.RespCode
	}
	return 0
}

func (x *EventProto) GetEventCode() int64 {
	if x != nil {
		return x.EventCode
	}
	return 0
}

func (x *EventProto) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *EventProto) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

var File_trade_bot_protobuf_src_tradeevent_proto protoreflect.FileDescriptor

var file_trade_bot_protobuf_src_tradeevent_proto_rawDesc = []byte{
	0x0a, 0x27, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x62, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22,
	0x72, 0x0a, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x42, 0x17, 0x5a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trade_bot_protobuf_src_tradeevent_proto_rawDescOnce sync.Once
	file_trade_bot_protobuf_src_tradeevent_proto_rawDescData = file_trade_bot_protobuf_src_tradeevent_proto_rawDesc
)

func file_trade_bot_protobuf_src_tradeevent_proto_rawDescGZIP() []byte {
	file_trade_bot_protobuf_src_tradeevent_proto_rawDescOnce.Do(func() {
		file_trade_bot_protobuf_src_tradeevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_trade_bot_protobuf_src_tradeevent_proto_rawDescData)
	})
	return file_trade_bot_protobuf_src_tradeevent_proto_rawDescData
}

var file_trade_bot_protobuf_src_tradeevent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trade_bot_protobuf_src_tradeevent_proto_goTypes = []interface{}{
	(*EventProto)(nil), // 0: trade_event_protobuf.EventProto
}
var file_trade_bot_protobuf_src_tradeevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trade_bot_protobuf_src_tradeevent_proto_init() }
func file_trade_bot_protobuf_src_tradeevent_proto_init() {
	if File_trade_bot_protobuf_src_tradeevent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trade_bot_protobuf_src_tradeevent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trade_bot_protobuf_src_tradeevent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trade_bot_protobuf_src_tradeevent_proto_goTypes,
		DependencyIndexes: file_trade_bot_protobuf_src_tradeevent_proto_depIdxs,
		MessageInfos:      file_trade_bot_protobuf_src_tradeevent_proto_msgTypes,
	}.Build()
	File_trade_bot_protobuf_src_tradeevent_proto = out.File
	file_trade_bot_protobuf_src_tradeevent_proto_rawDesc = nil
	file_trade_bot_protobuf_src_tradeevent_proto_goTypes = nil
	file_trade_bot_protobuf_src_tradeevent_proto_depIdxs = nil
}
