// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: trade_bot_protobuf/src/traderecord.proto

package traderecord

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeRecordArrProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*TradeRecordProto `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *TradeRecordArrProto) Reset() {
	*x = TradeRecordArrProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trade_bot_protobuf_src_traderecord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeRecordArrProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRecordArrProto) ProtoMessage() {}

func (x *TradeRecordArrProto) ProtoReflect() protoreflect.Message {
	mi := &file_trade_bot_protobuf_src_traderecord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRecordArrProto.ProtoReflect.Descriptor instead.
func (*TradeRecordArrProto) Descriptor() ([]byte, []int) {
	return file_trade_bot_protobuf_src_traderecord_proto_rawDescGZIP(), []int{0}
}

func (x *TradeRecordArrProto) GetData() []*TradeRecordProto {
	if x != nil {
		return x.Data
	}
	return nil
}

type TradeRecordProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quantity  int64   `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price     float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Action    string  `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Code      string  `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Id        string  `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	OrderTime string  `protobuf:"bytes,6,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	Status    string  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *TradeRecordProto) Reset() {
	*x = TradeRecordProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trade_bot_protobuf_src_traderecord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeRecordProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRecordProto) ProtoMessage() {}

func (x *TradeRecordProto) ProtoReflect() protoreflect.Message {
	mi := &file_trade_bot_protobuf_src_traderecord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRecordProto.ProtoReflect.Descriptor instead.
func (*TradeRecordProto) Descriptor() ([]byte, []int) {
	return file_trade_bot_protobuf_src_traderecord_proto_rawDescGZIP(), []int{1}
}

func (x *TradeRecordProto) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeRecordProto) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeRecordProto) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TradeRecordProto) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TradeRecordProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TradeRecordProto) GetOrderTime() string {
	if x != nil {
		return x.OrderTime
	}
	return ""
}

func (x *TradeRecordProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_trade_bot_protobuf_src_traderecord_proto protoreflect.FileDescriptor

var file_trade_bot_protobuf_src_traderecord_proto_rawDesc = []byte{
	0x0a, 0x28, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x62, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x22, 0x52, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x41, 0x72, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb7, 0x01, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42,
	0x18, 0x5a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_trade_bot_protobuf_src_traderecord_proto_rawDescOnce sync.Once
	file_trade_bot_protobuf_src_traderecord_proto_rawDescData = file_trade_bot_protobuf_src_traderecord_proto_rawDesc
)

func file_trade_bot_protobuf_src_traderecord_proto_rawDescGZIP() []byte {
	file_trade_bot_protobuf_src_traderecord_proto_rawDescOnce.Do(func() {
		file_trade_bot_protobuf_src_traderecord_proto_rawDescData = protoimpl.X.CompressGZIP(file_trade_bot_protobuf_src_traderecord_proto_rawDescData)
	})
	return file_trade_bot_protobuf_src_traderecord_proto_rawDescData
}

var file_trade_bot_protobuf_src_traderecord_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trade_bot_protobuf_src_traderecord_proto_goTypes = []interface{}{
	(*TradeRecordArrProto)(nil), // 0: trade_record_protobuf.TradeRecordArrProto
	(*TradeRecordProto)(nil),    // 1: trade_record_protobuf.TradeRecordProto
}
var file_trade_bot_protobuf_src_traderecord_proto_depIdxs = []int32{
	1, // 0: trade_record_protobuf.TradeRecordArrProto.data:type_name -> trade_record_protobuf.TradeRecordProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trade_bot_protobuf_src_traderecord_proto_init() }
func file_trade_bot_protobuf_src_traderecord_proto_init() {
	if File_trade_bot_protobuf_src_traderecord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trade_bot_protobuf_src_traderecord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeRecordArrProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trade_bot_protobuf_src_traderecord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeRecordProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trade_bot_protobuf_src_traderecord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trade_bot_protobuf_src_traderecord_proto_goTypes,
		DependencyIndexes: file_trade_bot_protobuf_src_traderecord_proto_depIdxs,
		MessageInfos:      file_trade_bot_protobuf_src_traderecord_proto_msgTypes,
	}.Build()
	File_trade_bot_protobuf_src_traderecord_proto = out.File
	file_trade_bot_protobuf_src_traderecord_proto_rawDesc = nil
	file_trade_bot_protobuf_src_traderecord_proto_goTypes = nil
	file_trade_bot_protobuf_src_traderecord_proto_depIdxs = nil
}
